# Generated by Django 2.0.1 on 2018-01-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('OsName', models.CharField(max_length=120)),
                ('OsManufacturer', models.CharField(max_length=120)),
                ('SysName', models.CharField(max_length=120)),
                ('Processor', models.CharField(max_length=200)),
            ],
        ),
    ]
