# Generated by Django 2.0.1 on 2018-01-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tims', '0002_auto_20180104_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='OsManufacturer',
            new_name='BrandName',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='SysName',
            new_name='ComputerName',
        ),
        migrations.AddField(
            model_name='computer',
            name='ExternalStorage',
            field=models.CharField(default='Hard Drive', max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='OsVersion',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='computer',
            name='Ram',
            field=models.CharField(default='64 GB', max_length=50),
        ),
    ]
