# Generated by Django 2.0.1 on 2018-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tims', '0004_auto_20180104_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='SerialKey',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
