# Generated by Django 2.0.1 on 2018-01-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tims', '0005_computer_serialkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='Location',
            field=models.CharField(default='Pune', max_length=120),
        ),
    ]
