# Generated by Django 2.0.1 on 2018-01-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tims', '0008_auto_20180105_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='HostName',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='SerialKey',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='computer',
            unique_together=set(),
        ),
    ]
