# Generated by Django 2.0.1 on 2018-01-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tims', '0009_auto_20180105_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='OsName',
            field=models.CharField(choices=[('window', 'Windows'), ('linux', 'Linux')], default='Windows', max_length=120),
        ),
    ]
